# Generated by Django 5.1.1 on 2024-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('designation', models.CharField(choices=[('manager', 'Manager'), ('full stact developer', 'Full Stack Developer'), ('android developer', 'Android Developer'), ('web developer', 'Web Developer'), ('frontend developer', 'Frontend Developer'), ('web designer', 'Web Designer')], max_length=50)),
                ('short_description', models.TextField()),
            ],
        ),
    ]
