# Generated by Django 5.1.1 on 2024-09-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('manager', 'Manager'), ('full stact developer', 'Full Stack Developer'), ('android developer', 'Android Developer'), ('web developer', 'Web Developer'), ('frontend developer', 'Frontend Developer'), ('web designer', 'Web Designer')], default='Manager', max_length=50),
        ),
    ]
