# Generated by Django 5.1.1 on 2024-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('manager', 'Manager'), ('full stact developer', 'Full Stack Developer'), ('android developer', 'Android Developer'), ('web developer', 'Web Developer'), ('frontend developer', 'Frontend Developer'), ('web designer', 'Web Designer')], default='manager', max_length=50),
        ),
    ]
